# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-11-06 12:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Programmers_profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=30)),
                ('profile_photo', models.ImageField(null=True, upload_to='profile_photos/')),
                ('github_link', models.CharField(max_length=30)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('degree', models.CharField(max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('project_image', models.ImageField(null=True, upload_to='project_images/')),
                ('description', models.CharField(max_length=300)),
                ('link', models.URLField(db_index=True, max_length=128, null=True, unique=True)),
                ('posred_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('programmers', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='geek.Programmers_profile')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
