# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-11-07 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geek', '0004_project_videofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_names', models.CharField(max_length=60)),
                ('business_name', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=30)),
                ('phone', models.IntegerField(default=0)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
            ],
        ),
    ]
