# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-11-07 12:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geek', '0006_auto_20191107_1359'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partner',
            old_name='partner_user',
            new_name='user',
        ),
    ]
