# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-11-07 18:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geek', '0007_auto_20191107_1427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='partner_profile',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='user',
        ),
        migrations.DeleteModel(
            name='Partner',
        ),
    ]
